# hosts.yml
#
# List of hosts to be created by Vagrant. Your `site.yml` should contain
# the same hosts. This file controls the Vagrant settings, `site.yml` the
# Ansible-related stuff.
---
-
  name: srv001
  ip: 192.168.56.10
-
  name: srv002
  ip: 192.168.56.11

